import express from "express";
import isAuth from "../controllers/users/isAuth.js";
import getEvents from "../controllers/Events/getEvents.js";
import getEventById from "../controllers/Events/getEventById.js";
import getEventByTag from "../controllers/Events/getEventByTag.js";
import getEventByUser from "../controllers/Events/getEventByUser.js";
import createEvent from "../controllers/Events/createEvent.js";
import deleteEvent from "../controllers/Events/deleteEvent.js";
import editEvent from "../controllers/Events/editEvent.js";
import isAdmin from "../controllers/users/isAdmin.js";
import addTagToEvent from "../controllers/Events/addTagToEvent.js";
import removeTagFromEvent from "../controllers/Events/removeTagFromEvent.js";
import addUserToEvent from "../controllers/Events/addUserToEvent.js";
import removeUserFromEvent from "../controllers/Events/removeUserFromEvent.js";

const app = express.Router();
app.get("/api/events", getEvents);
app.get("/api/events/:id", getEventById);
app.get("/api/events/tag/:tagId", getEventByTag);
app.get("/api/events/user/:userId", isAuth, getEventByUser);
app.post("/api/events", isAdmin, createEvent);
app.put("/api/events/:id", isAdmin, editEvent);
app.delete("/api/events/:id", isAdmin, deleteEvent);
app.post("/api/events/:eventId/tags/:tagId", isAdmin, addTagToEvent);
app.delete("/api/events/:eventId/tags/:tagId", isAdmin, removeTagFromEvent);
app.post("/api/events/:eventId/users/:userId", isAuth, addUserToEvent);
app.delete("/api/events/:eventId/users/:userId", isAuth, removeUserFromEvent);
export default app;
